### ISSUE TITLE
Echodoc breaks i_0_CTRL-D

### ISSUE THREAD

**Issue by fenuks** [Shougo/echodoc.vim#91]
i_0_CTRL-D removes all indent in current line. Similar mapping i_^_CTRL-D is also broken.

```
$ nvim --version
NVIM v0.5.0-dev+1081-g230f2ff38
(...)
```

Minimal vimrc to reproduce problem.
```
call plug#begin('~/.config/nvim/plugged')
Plug 'Shougo/echodoc.vim'
let g:echodoc#enable_at_startup = 1
call plug#end()
```

**Comment by Shougo** [comment]
Please upload the reproduce instruction.
If not, OK.  I will close it.

**Comment by Shougo** [comment]
The example
https://github.com/Shougo/echodoc.vim/issues/83

**Comment by Shougo** [comment]
Fixed.

**Comment by Shougo** [comment]
deoplete conflicts with the mappings.
But I cannot fix the problem...

**Comment by fenuks** [comment]
I was just writing how to reproduce it in more detail – you are fast. ;)

It fixes this problem for me with just echodoc.vim in my minimal configuration pasted in this issue, but it still doesn't work with my full vim config that also uses deoplete, as you wrote.

**Comment by Shougo** [comment]
> It fixes this problem for me with just echodoc.vim in my minimal configuration pasted in this issue, but it still doesn't work with my full vim config that also uses deoplete, as you wrote.

I have tested.
If deoplete call Vim API it breaks mappings.
Gave up.

**Comment by Shougo** [comment]
It seems neovim's problem.  In Vim8, the problem is not exists.
So you can create the issue for neovim.

**Comment by fenuks** [comment]
Alright, I will file an issue. Thank you.
